package problem;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Problem2SumOfEvenFibonacciNumbers {

    public static void main(String[] args) {

        int sum = sumOfEvenFibonacci(4_000_000);
        System.out.println("Sum: " + sum);
    }

    public static int sumOfEvenFibonacci(int limit) {

        if (limit < 2) return limit;

        int prev = 1, sum = 2, next = 0;
        for (int i = 2; i < limit; ) {

            next = i + prev;
            prev = i;
            i = next;

            if (next % 2 == 0) sum += next;
        }

        return sum;
    }
}
